In [1]:
import numpy as np

**Escalares**

In [2]:
s = 5

**Vectores**

In [4]:
# Vector fila
v = np.array( [5, -2, 4] )
v

array([ 5, -2,  4])

**Matriz**

In [9]:
# Matriz 2X3
m = np.array([
    [5, 12, 6],
    [-3, 0, 14]
    ])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

**Tipos de Datos**

In [7]:
type(s)

int

In [8]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [10]:
s_array = np.array(5)
type(s_array)

numpy.ndarray

**Data Shapes**

In [12]:
# Matriz 2X3
m.shape

(2, 3)

In [13]:
# Vector fila
v.shape

(3,)

**Vector Columna**

In [16]:
# Pasar de vector fila a vector columna
v.reshape(3, 1)

array([[ 5],
       [-2],
       [ 4]])

In [15]:
v.shape

(3,)