In [1]:
import numpy as np

**Producto Escalar entre Vectores**

La multiplicación entre dos vectores (dot) genera como resultado un escalar.

In [2]:
x = np.array([2, 8, -4])
y = np.array([1, -7, 3])

In [3]:
np.dot(x, y)

-66

In [4]:
u = np.array([0, 2, 5, 8])
v = np.array([20, 3, 4, -1])

In [5]:
np.dot(u, v)

18

**Escalar * Vector**

In [6]:
x

array([ 2,  8, -4])

In [7]:
5 * x

array([ 10,  40, -20])

**Producto Escalar entre Matrices**

In [8]:
A = np.array([
    [5, 12, 6],
    [-3, 0, 14]
])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

**Matriz * Matriz**

**Únicamente se puede multiplicar una matriz mxn por una matriz nxk**

Ejemplo: Se puede multiplicar una matriz de 2x3 por una 3xk

**Una multiplicación entre una matriz mxn por una matriz nxk dará como resultado una matriz mxk**

Ejemplo: Una matriz 2x3 por una matriz 3x6 da como resultado una matriz 2x6

Ejemplo 1 de producto escalar entre matrices en numpy

In [10]:
A = np.array([
    [5, 12, 6],
    [-3, 0, 14]
])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [11]:
B = np.array([
    [2, -1],
    [8, 0],
    [3, 0]
])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [12]:
np.dot(A, B)

array([[124,  -5],
       [ 36,   3]])

Scalar * Matriz

In [9]:
3 * A

array([[15, 36, 18],
       [-9,  0, 42]])