### ¿Qué es un tensor?

Es el concepto general que engloba todos los tipos de arreglos del álgebra lineal (escalares (tensor 1x1), vectores (tensor mx1), matrices (tensor mxn), tensor de rango 3 (kXmXn))

In [1]:
import numpy as np

**Creando un tensor**

In [2]:
m1 = np.array([
    [5, 12, 6],
    [-3, 0, 14]
])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([
    [9, 8, 7],
    [1, 3, -5]
])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

**Verificamos su shape**

Tensor de rango 3

In [5]:
t.shape

(2, 2, 3)